---
apiVersion: cstor.openebs.io/v1
kind: CStorVolumePolicy
metadata:
  name: app-target-affinity-policy
  namespace: openebs
spec:
  target:
    affinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: openebs.io/target-affinity
            operator: In
            values:
            - app-label
        topologyKey: kubernetes.io/hostname
        namespaces: ["app-namespace"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: testclass
provisioner: cstor.csi.openebs.io
allowVolumeExpansion: true
volumeBindingMode: Immediate
parameters:
  replicaCount: "3"
  cstorPoolCluster: "pool-name"
  cas-type: "cstor"
  cstorVolumePolicy: "app-target-affinity-policy"

